export function createInitialState(highestUnlockedLevel = 0) {
  return {
    mode: "title",
    level: 0,
    t: 0,
    dist: 0,
    score: 0,
    vested: 0,
    health: 3,
    maxHealth: 3,
    trabajeen: 3,
    shoutPulse: 0,
    shoutText: 0,
    invuln: 0,
    kick: 0,
    player: { x: 170, y: 240, vy: 0, w: 70, h: 38 },
    squad: [],
    ents: [],
    parts: [],
    effects: [],
    shakeLife: 0,
    shakeDuration: 1,
    damageFlash: 0,
    transitionTimer: 0,
    transitionReward: 0,
    bubbles: [],
    links: [],
    linked: 0,
    needLink: 0,
    banner: null,
    bannerLife: 0,
    winTimer: 0,
    checkpoint: highestUnlockedLevel,
    runSeed: 0,
    finishing: false,
    hurtTimer: 0
  };
}
